# Generated by Django 5.0.3 on 2024-03-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Textos",
        ),
        migrations.AddField(
            model_name="arquivos",
            name="tipo",
            field=models.CharField(
                choices=[("A", "Arquivo"), ("T", "Texto")], default="A", max_length=1
            ),
        ),
    ]
